import { nextConfig } from "@vyora/config/eslint/next";

/** @type {import("eslint").Linter.Config[]} */
export default [
  ...nextConfig,
  {
    // Generated by Serwist at build time.
    ignores: [".next/**", "public/sw.js", "public/swe-worker-*.js"],
  },
];
