import { nextConfig } from "@vyora/config/eslint/next";

/** @type {import("eslint").Linter.Config[]} */
export default [
  ...nextConfig,
  {
    ignores: [
      ".next/**",
      // Generated by Serwist at build time.
      "public/sw.js",
      "public/swe-worker-*.js",
      // Vendored sqlite-wasm, copied verbatim from the upstream package. It is
      // served unbundled on purpose (webpack breaks its OPFS proxy worker URL),
      // and it is not ours to lint or fix.
      "public/sqlite/**",
    ],
  },
];
