// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(app)/accounting/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/accounting">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/accounting/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/administration/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/administration">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/administration/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/assistant/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/assistant">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/assistant/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/credit-radar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/credit-radar">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/credit-radar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/crm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/crm">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/crm/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/customers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/customers">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/customers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/expenses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/expenses">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/expenses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/gst/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/gst">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/gst/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/inventory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inventory">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/inventory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/invoice/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/invoice/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/invoice/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/marketing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/marketing">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/marketing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/payments">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/products/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/products">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/products/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/promotions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/promotions">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/promotions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/purchase/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/purchase">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/purchase/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/reconcile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reconcile">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/reconcile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/sales/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sales">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/sales/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/scan-sell/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/scan-sell">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/scan-sell/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/snap-bill/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/snap-bill">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/snap-bill/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/stock-radar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stock-radar">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/stock-radar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/subscriptions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/subscriptions">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/subscriptions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/suppliers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/suppliers">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/suppliers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/support">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(app)/voice-bill/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/voice-bill">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/voice-bill/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(auth)/welcome/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/welcome">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/welcome/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/download/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/download">> = Specific
  const handler = {} as typeof import("../../src/app/download/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/~offline/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/~offline">> = Specific
  const handler = {} as typeof import("../../src/app/~offline/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ai/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai">> = Specific
  const handler = {} as typeof import("../../src/app/api/ai/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ocr/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ocr">> = Specific
  const handler = {} as typeof import("../../src/app/api/ocr/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/promo/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/promo">> = Specific
  const handler = {} as typeof import("../../src/app/api/promo/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/voice-bill/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/voice-bill">> = Specific
  const handler = {} as typeof import("../../src/app/api/voice-bill/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../src/app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/(app)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(app)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
