-- Seed business_types with the verticals the engine defines.
--
-- GENERATED by packages/core/scripts/generate-seed-migration.mjs — do not edit
-- by hand. Regenerate from the seed and add a NEW migration instead; the rows
-- are upserted on key, so re-running is safe and an edited vertical updates in
-- place rather than duplicating.
--
-- Nothing hardcodes a key: onboarding lists whatever rows exist here, and
-- create_workspace resolves the key it is handed. So keys may change.

insert into public.business_types (key, label, is_system, config)
values
  ('pharmacy', 'Pharmacy', true, '{
  "businessType": "pharmacy",
  "label": "Pharmacy",
  "sector": "Chemist & medical",
  "letter": "Rx",
  "hue": 150,
  "fields": {
    "required": [
      {
        "key": "item_name",
        "label": "Item name",
        "type": "text",
        "required": true
      },
      {
        "key": "batch_no",
        "label": "Batch No",
        "type": "text",
        "required": true
      },
      {
        "key": "expiry",
        "label": "Expiry",
        "type": "date",
        "required": true
      },
      {
        "key": "mrp",
        "label": "MRP",
        "type": "currency",
        "required": true
      },
      {
        "key": "qty",
        "label": "Qty",
        "type": "number",
        "required": true
      },
      {
        "key": "gst",
        "label": "GST",
        "type": "percent",
        "required": true
      }
    ],
    "optional": [
      {
        "key": "schedule",
        "label": "Schedule (H/H1/X)",
        "type": "select",
        "required": false,
        "options": [
          {
            "value": "H",
            "label": "H"
          },
          {
            "value": "H1",
            "label": "H1"
          },
          {
            "value": "X",
            "label": "X"
          }
        ]
      },
      {
        "key": "hsn",
        "label": "HSN",
        "type": "text",
        "required": false
      },
      {
        "key": "manufacturer",
        "label": "Manufacturer",
        "type": "text",
        "required": false
      },
      {
        "key": "rack",
        "label": "Rack",
        "type": "text",
        "required": false
      }
    ]
  },
  "validations": [
    {
      "message": "Expiry date must be after today",
      "check": {
        "kind": "date_after",
        "field": "expiry",
        "than": "$today"
      }
    },
    {
      "message": "Batch No mandatory for scheduled drugs",
      "check": {
        "kind": "required_when",
        "field": "batch_no",
        "when": {
          "op": "in",
          "field": "schedule",
          "values": [
            "H",
            "H1",
            "X"
          ]
        }
      }
    },
    {
      "message": "Selling price cannot exceed MRP",
      "check": {
        "kind": "lte_field",
        "field": "rate",
        "than": "mrp"
      }
    },
    {
      "message": "Qty cannot exceed available stock",
      "check": {
        "kind": "lte_field",
        "field": "qty",
        "than": "$available_stock"
      }
    },
    {
      "message": "Schedule-H sale requires prescription reference",
      "check": {
        "kind": "note"
      }
    }
  ],
  "gst": {
    "defaultLabel": "12%",
    "default": {
      "kind": "fixed",
      "bps": 1200
    },
    "slabs": [
      {
        "applies": "Life-saving / exempt drugs",
        "rate": {
          "kind": "range",
          "minBps": 0,
          "maxBps": 500,
          "bps": 500
        }
      },
      {
        "applies": "General medicines",
        "rate": {
          "kind": "fixed",
          "bps": 1200
        }
      },
      {
        "applies": "Wellness & OTC",
        "rate": {
          "kind": "fixed",
          "bps": 1800
        }
      }
    ]
  },
  "invoice": {
    "template": "TAX INVOICE",
    "columns": [
      "Item",
      "Batch",
      "Exp",
      "HSN",
      "Qty",
      "MRP",
      "Rate",
      "GST",
      "Amount"
    ],
    "extras": [
      "Drug license no.",
      "Pharmacist sign"
    ]
  },
  "reports": [
    "GSTR-1",
    "Expiry & batch register",
    "Schedule-H register",
    "Fast movers"
  ]
}'::jsonb),
  ('medical', 'Medical Store', true, '{
  "businessType": "medical",
  "label": "Medical Store",
  "sector": "Retail chemist",
  "letter": "Ms",
  "hue": 158,
  "fields": {
    "required": [
      {
        "key": "item_name",
        "label": "Item name",
        "type": "text",
        "required": true
      },
      {
        "key": "batch_no",
        "label": "Batch No",
        "type": "text",
        "required": true
      },
      {
        "key": "expiry",
        "label": "Expiry",
        "type": "date",
        "required": true
      },
      {
        "key": "mrp",
        "label": "MRP",
        "type": "currency",
        "required": true
      },
      {
        "key": "qty",
        "label": "Qty",
        "type": "number",
        "required": true
      },
      {
        "key": "gst",
        "label": "GST",
        "type": "percent",
        "required": true
      }
    ],
    "optional": [
      {
        "key": "prescription_upload",
        "label": "Prescription upload",
        "type": "file",
        "required": false
      },
      {
        "key": "schedule",
        "label": "Schedule",
        "type": "select",
        "required": false,
        "options": [
          {
            "value": "H",
            "label": "H"
          },
          {
            "value": "H1",
            "label": "H1"
          },
          {
            "value": "X",
            "label": "X"
          }
        ]
      },
      {
        "key": "hsn",
        "label": "HSN",
        "type": "text",
        "required": false
      },
      {
        "key": "salt_composition",
        "label": "Salt / composition",
        "type": "text",
        "required": false
      }
    ]
  },
  "validations": [
    {
      "message": "Expiry must be after today",
      "check": {
        "kind": "date_after",
        "field": "expiry",
        "than": "$today"
      }
    },
    {
      "message": "Substitute suggested if out of stock",
      "check": {
        "kind": "note"
      }
    },
    {
      "message": "Selling price ≤ MRP",
      "check": {
        "kind": "lte_field",
        "field": "rate",
        "than": "mrp"
      }
    },
    {
      "message": "Rx upload required for schedule drugs",
      "check": {
        "kind": "required_when",
        "field": "prescription_upload",
        "when": {
          "op": "in",
          "field": "schedule",
          "values": [
            "H",
            "H1",
            "X"
          ]
        }
      }
    }
  ],
  "gst": {
    "defaultLabel": "12%",
    "default": {
      "kind": "fixed",
      "bps": 1200
    },
    "slabs": [
      {
        "applies": "Exempt drugs",
        "rate": {
          "kind": "fixed",
          "bps": 0
        }
      },
      {
        "applies": "Most medicines",
        "rate": {
          "kind": "fixed",
          "bps": 1200
        }
      },
      {
        "applies": "Cosmetics & devices",
        "rate": {
          "kind": "fixed",
          "bps": 1800
        }
      }
    ]
  },
  "invoice": {
    "template": "TAX INVOICE",
    "columns": [
      "Item",
      "Batch",
      "Exp",
      "Qty",
      "MRP",
      "Rate",
      "GST",
      "Amount"
    ],
    "extras": [
      "Drug license no."
    ]
  },
  "reports": [
    "GSTR-1",
    "Expiry alerts",
    "Salt-wise sales",
    "Purchase returns"
  ]
}'::jsonb),
  ('grocery', 'Grocery', true, '{
  "businessType": "grocery",
  "label": "Grocery",
  "sector": "Daily needs",
  "letter": "Gr",
  "hue": 130,
  "fields": {
    "required": [
      {
        "key": "item_name",
        "label": "Item name",
        "type": "text",
        "required": true
      },
      {
        "key": "unit",
        "label": "Weight / unit",
        "type": "select",
        "required": true,
        "options": [
          {
            "value": "pcs",
            "label": "Pieces"
          },
          {
            "value": "kg",
            "label": "Kilogram"
          },
          {
            "value": "g",
            "label": "Gram"
          },
          {
            "value": "ltr",
            "label": "Litre"
          },
          {
            "value": "ml",
            "label": "Millilitre"
          },
          {
            "value": "box",
            "label": "Box"
          },
          {
            "value": "mtr",
            "label": "Metre"
          }
        ]
      },
      {
        "key": "mrp",
        "label": "MRP",
        "type": "currency",
        "required": true
      },
      {
        "key": "qty",
        "label": "Qty",
        "type": "number",
        "required": true
      },
      {
        "key": "gst",
        "label": "GST",
        "type": "percent",
        "required": true
      }
    ],
    "optional": [
      {
        "key": "barcode",
        "label": "Barcode",
        "type": "scan",
        "required": false,
        "scanKind": "barcode"
      },
      {
        "key": "brand",
        "label": "Brand",
        "type": "text",
        "required": false
      },
      {
        "key": "hsn",
        "label": "HSN",
        "type": "text",
        "required": false
      }
    ]
  },
  "validations": [
    {
      "message": "Weight / quantity must be greater than 0",
      "check": {
        "kind": "gt",
        "field": "qty",
        "value": 0
      }
    },
    {
      "message": "Barcode must be unique",
      "check": {
        "kind": "unique",
        "fields": [
          "barcode"
        ]
      }
    },
    {
      "message": "Loose items priced per unit weight",
      "check": {
        "kind": "note"
      }
    }
  ],
  "gst": {
    "defaultLabel": "5%",
    "default": {
      "kind": "fixed",
      "bps": 500
    },
    "slabs": [
      {
        "applies": "Unbranded staples",
        "rate": {
          "kind": "fixed",
          "bps": 0
        }
      },
      {
        "applies": "Packaged food",
        "rate": {
          "kind": "fixed",
          "bps": 500
        }
      },
      {
        "applies": "Processed / branded",
        "rate": {
          "kind": "range",
          "minBps": 1200,
          "maxBps": 1800,
          "bps": 1800
        }
      }
    ]
  },
  "invoice": {
    "template": "RETAIL BILL",
    "columns": [
      "Item",
      "Unit",
      "Qty",
      "Rate",
      "GST",
      "Amount"
    ],
    "extras": [
      "Round-off",
      "Thank-you note"
    ]
  },
  "reports": [
    "Fast movers",
    "Low stock",
    "GST summary",
    "Daily sales"
  ]
}'::jsonb),
  ('kirana', 'Kirana', true, '{
  "businessType": "kirana",
  "label": "Kirana",
  "sector": "Neighbourhood store",
  "letter": "Kr",
  "hue": 120,
  "fields": {
    "required": [
      {
        "key": "item_name",
        "label": "Item name",
        "type": "text",
        "required": true
      },
      {
        "key": "qty",
        "label": "Qty",
        "type": "number",
        "required": true
      },
      {
        "key": "rate",
        "label": "Rate",
        "type": "currency",
        "required": true
      }
    ],
    "optional": [
      {
        "key": "unit",
        "label": "Unit",
        "type": "select",
        "required": false,
        "options": [
          {
            "value": "pcs",
            "label": "Pieces"
          },
          {
            "value": "kg",
            "label": "Kilogram"
          },
          {
            "value": "g",
            "label": "Gram"
          },
          {
            "value": "ltr",
            "label": "Litre"
          },
          {
            "value": "ml",
            "label": "Millilitre"
          },
          {
            "value": "box",
            "label": "Box"
          },
          {
            "value": "mtr",
            "label": "Metre"
          }
        ]
      },
      {
        "key": "customer_khata",
        "label": "Customer khata",
        "type": "select",
        "required": false,
        "options": [
          {
            "value": "cash",
            "label": "Cash"
          },
          {
            "value": "khata",
            "label": "Khata (credit)"
          }
        ]
      },
      {
        "key": "gst",
        "label": "GST",
        "type": "percent",
        "required": false
      }
    ]
  },
  "validations": [
    {
      "message": "Credit (khata) within customer limit",
      "check": {
        "kind": "note"
      }
    },
    {
      "message": "Composition dealers omit tax breakup",
      "check": {
        "kind": "note"
      }
    },
    {
      "message": "Daily cash reconciliation prompt",
      "check": {
        "kind": "note"
      }
    }
  ],
  "gst": {
    "defaultLabel": "Composition 1%",
    "default": {
      "kind": "fixed",
      "bps": 100
    },
    "composition": {
      "rateBps": 100
    },
    "slabs": [
      {
        "applies": "Composition scheme",
        "rate": {
          "kind": "fixed",
          "bps": 100
        }
      },
      {
        "applies": "Exempt goods",
        "rate": {
          "kind": "fixed",
          "bps": 0
        }
      }
    ]
  },
  "invoice": {
    "template": "BILL OF SUPPLY",
    "columns": [
      "Item",
      "Qty",
      "Rate",
      "Amount"
    ],
    "extras": [
      "Khata balance",
      "Composition dealer"
    ]
  },
  "reports": [
    "Khata outstanding",
    "Daily sales",
    "Top customers"
  ]
}'::jsonb),
  ('electronics', 'Electronics', true, '{
  "businessType": "electronics",
  "label": "Electronics",
  "sector": "Appliances & gadgets",
  "letter": "El",
  "hue": 245,
  "fields": {
    "required": [
      {
        "key": "item_name",
        "label": "Item name",
        "type": "text",
        "required": true
      },
      {
        "key": "brand",
        "label": "Brand",
        "type": "select",
        "required": true,
        "options": [
          {
            "value": "samsung",
            "label": "Samsung"
          },
          {
            "value": "lg",
            "label": "LG"
          },
          {
            "value": "sony",
            "label": "Sony"
          },
          {
            "value": "godrej",
            "label": "Godrej"
          },
          {
            "value": "whirlpool",
            "label": "Whirlpool"
          },
          {
            "value": "other",
            "label": "Other"
          }
        ]
      },
      {
        "key": "model",
        "label": "Model",
        "type": "text",
        "required": true
      },
      {
        "key": "serial_no",
        "label": "Serial No",
        "type": "text",
        "required": true
      },
      {
        "key": "mrp",
        "label": "MRP",
        "type": "currency",
        "required": true
      },
      {
        "key": "qty",
        "label": "Qty",
        "type": "number",
        "required": true
      },
      {
        "key": "gst",
        "label": "GST",
        "type": "percent",
        "required": true
      }
    ],
    "optional": [
      {
        "key": "warranty",
        "label": "Warranty",
        "type": "select",
        "required": false,
        "options": [
          {
            "value": "none",
            "label": "No warranty"
          },
          {
            "value": "6m",
            "label": "6 months"
          },
          {
            "value": "1y",
            "label": "1 year"
          },
          {
            "value": "2y",
            "label": "2 years"
          },
          {
            "value": "3y",
            "label": "3 years"
          }
        ]
      },
      {
        "key": "hsn",
        "label": "HSN",
        "type": "text",
        "required": false
      },
      {
        "key": "extended_warranty",
        "label": "Extended warranty",
        "type": "select",
        "required": false,
        "options": [
          {
            "value": "none",
            "label": "None"
          },
          {
            "value": "1y",
            "label": "1 year"
          },
          {
            "value": "2y",
            "label": "2 years"
          },
          {
            "value": "3y",
            "label": "3 years"
          }
        ]
      }
    ]
  },
  "validations": [
    {
      "message": "Serial No must be unique",
      "check": {
        "kind": "unique",
        "fields": [
          "serial_no"
        ]
      }
    },
    {
      "message": "Warranty end auto-calculated from sale date",
      "check": {
        "kind": "note"
      }
    },
    {
      "message": "Qty ≤ stock",
      "check": {
        "kind": "lte_field",
        "field": "qty",
        "than": "$available_stock"
      }
    }
  ],
  "gst": {
    "defaultLabel": "18%",
    "default": {
      "kind": "fixed",
      "bps": 1800
    },
    "slabs": [
      {
        "applies": "Most electronics",
        "rate": {
          "kind": "fixed",
          "bps": 1800
        }
      },
      {
        "applies": "Large appliances / TVs",
        "rate": {
          "kind": "fixed",
          "bps": 2800
        }
      }
    ]
  },
  "invoice": {
    "template": "TAX INVOICE",
    "columns": [
      "Item",
      "Brand",
      "Model",
      "Serial",
      "Warranty",
      "Qty",
      "Rate",
      "GST",
      "Amount"
    ],
    "extras": [
      "Warranty terms",
      "Serial recorded"
    ]
  },
  "reports": [
    "Warranty tracker",
    "Serial ledger",
    "Sales trend",
    "Service claims"
  ]
}'::jsonb),
  ('mobile', 'Mobile Shop', true, '{
  "businessType": "mobile",
  "label": "Mobile Shop",
  "sector": "Phones & accessories",
  "letter": "Mb",
  "hue": 265,
  "fields": {
    "required": [
      {
        "key": "brand",
        "label": "Brand",
        "type": "select",
        "required": true,
        "options": [
          {
            "value": "samsung",
            "label": "Samsung"
          },
          {
            "value": "xiaomi",
            "label": "Xiaomi"
          },
          {
            "value": "realme",
            "label": "Realme"
          },
          {
            "value": "vivo",
            "label": "Vivo"
          },
          {
            "value": "oppo",
            "label": "Oppo"
          },
          {
            "value": "apple",
            "label": "Apple"
          },
          {
            "value": "oneplus",
            "label": "OnePlus"
          },
          {
            "value": "other",
            "label": "Other"
          }
        ]
      },
      {
        "key": "model",
        "label": "Model",
        "type": "text",
        "required": true
      },
      {
        "key": "imei",
        "label": "IMEI",
        "type": "scan",
        "required": true,
        "scanKind": "imei"
      },
      {
        "key": "price",
        "label": "Price",
        "type": "currency",
        "required": true
      },
      {
        "key": "gst",
        "label": "GST",
        "type": "percent",
        "required": true
      }
    ],
    "optional": [
      {
        "key": "serial_no",
        "label": "Serial No",
        "type": "text",
        "required": false
      },
      {
        "key": "warranty",
        "label": "Warranty",
        "type": "select",
        "required": false,
        "options": [
          {
            "value": "none",
            "label": "No warranty"
          },
          {
            "value": "6m",
            "label": "6 months"
          },
          {
            "value": "1y",
            "label": "1 year"
          },
          {
            "value": "2y",
            "label": "2 years"
          },
          {
            "value": "3y",
            "label": "3 years"
          }
        ]
      },
      {
        "key": "colour",
        "label": "Colour",
        "type": "select",
        "required": false,
        "options": [
          {
            "value": "black",
            "label": "Black"
          },
          {
            "value": "white",
            "label": "White"
          },
          {
            "value": "blue",
            "label": "Blue"
          },
          {
            "value": "red",
            "label": "Red"
          },
          {
            "value": "green",
            "label": "Green"
          },
          {
            "value": "grey",
            "label": "Grey"
          },
          {
            "value": "silver",
            "label": "Silver"
          },
          {
            "value": "gold",
            "label": "Gold"
          },
          {
            "value": "other",
            "label": "Other"
          }
        ]
      },
      {
        "key": "storage",
        "label": "Storage",
        "type": "select",
        "required": false,
        "options": [
          {
            "value": "32gb",
            "label": "32 GB"
          },
          {
            "value": "64gb",
            "label": "64 GB"
          },
          {
            "value": "128gb",
            "label": "128 GB"
          },
          {
            "value": "256gb",
            "label": "256 GB"
          },
          {
            "value": "512gb",
            "label": "512 GB"
          }
        ]
      }
    ]
  },
  "validations": [
    {
      "message": "IMEI must be 15 digits and unique",
      "check": {
        "kind": "length",
        "field": "imei",
        "exact": 15,
        "charset": "digits"
      }
    },
    {
      "message": "IMEI must be 15 digits and unique",
      "check": {
        "kind": "unique",
        "fields": [
          "imei"
        ]
      }
    },
    {
      "message": "Warranty auto-registered on sale",
      "check": {
        "kind": "note"
      }
    },
    {
      "message": "Exchange value deducted before GST",
      "check": {
        "kind": "note"
      }
    }
  ],
  "gst": {
    "defaultLabel": "18%",
    "default": {
      "kind": "fixed",
      "bps": 1800
    },
    "slabs": [
      {
        "applies": "Phones & tablets",
        "rate": {
          "kind": "fixed",
          "bps": 1800
        }
      },
      {
        "applies": "Accessories",
        "rate": {
          "kind": "fixed",
          "bps": 1800
        }
      }
    ]
  },
  "invoice": {
    "template": "TAX INVOICE",
    "columns": [
      "Brand",
      "Model",
      "IMEI",
      "Warranty",
      "Qty",
      "Rate",
      "GST",
      "Amount"
    ],
    "extras": [
      "IMEI printed",
      "Warranty card"
    ]
  },
  "reports": [
    "IMEI ledger",
    "Warranty tracker",
    "GSTR-1",
    "Exchange log"
  ]
}'::jsonb),
  ('restaurant', 'Restaurant', true, '{
  "businessType": "restaurant",
  "label": "Restaurant",
  "sector": "Dine-in & delivery",
  "letter": "Rt",
  "hue": 35,
  "fields": {
    "required": [
      {
        "key": "item_name",
        "label": "Item name",
        "type": "text",
        "required": true
      },
      {
        "key": "qty",
        "label": "Qty",
        "type": "number",
        "required": true
      },
      {
        "key": "rate",
        "label": "Rate",
        "type": "currency",
        "required": true
      },
      {
        "key": "order_type",
        "label": "Order type",
        "type": "select",
        "required": true,
        "options": [
          {
            "value": "dine_in",
            "label": "Dine-in"
          },
          {
            "value": "takeaway",
            "label": "Takeaway"
          },
          {
            "value": "delivery",
            "label": "Delivery"
          }
        ]
      },
      {
        "key": "gst",
        "label": "GST",
        "type": "percent",
        "required": true
      }
    ],
    "optional": [
      {
        "key": "table",
        "label": "Table",
        "type": "select",
        "required": false,
        "options": [
          {
            "value": "t1",
            "label": "Table 1"
          },
          {
            "value": "t2",
            "label": "Table 2"
          },
          {
            "value": "t3",
            "label": "Table 3"
          },
          {
            "value": "t4",
            "label": "Table 4"
          },
          {
            "value": "t5",
            "label": "Table 5"
          },
          {
            "value": "t6",
            "label": "Table 6"
          }
        ]
      },
      {
        "key": "waiter",
        "label": "Waiter",
        "type": "select",
        "required": false,
        "options": [
          {
            "value": "unassigned",
            "label": "Unassigned"
          },
          {
            "value": "staff_1",
            "label": "Staff 1"
          },
          {
            "value": "staff_2",
            "label": "Staff 2"
          },
          {
            "value": "staff_3",
            "label": "Staff 3"
          }
        ]
      },
      {
        "key": "kot_no",
        "label": "KOT No",
        "type": "auto",
        "required": false
      },
      {
        "key": "kitchen_notes",
        "label": "Kitchen notes",
        "type": "text",
        "required": false
      }
    ]
  },
  "validations": [
    {
      "message": "Table required for dine-in orders",
      "check": {
        "kind": "required_when",
        "field": "table",
        "when": {
          "op": "eq",
          "field": "order_type",
          "value": "dine_in"
        }
      }
    },
    {
      "message": "KOT auto-generated on confirm",
      "check": {
        "kind": "note"
      }
    },
    {
      "message": "Service charge shown separately from GST",
      "check": {
        "kind": "note"
      }
    }
  ],
  "gst": {
    "defaultLabel": "5%",
    "default": {
      "kind": "fixed",
      "bps": 500
    },
    "slabs": [
      {
        "applies": "Standard restaurant",
        "rate": {
          "kind": "fixed",
          "bps": 500
        },
        "itcBlocked": true
      },
      {
        "applies": "AC / hotel ≥ ₹7,500 room",
        "rate": {
          "kind": "fixed",
          "bps": 1800
        },
        "when": {
          "op": "gte",
          "field": "tariff",
          "value": 750000
        }
      }
    ]
  },
  "invoice": {
    "template": "TAX INVOICE",
    "columns": [
      "Item",
      "Qty",
      "Rate",
      "Amount"
    ],
    "extras": [
      "KOT reference",
      "Service charge",
      "Table / parcel"
    ]
  },
  "reports": [
    "Table turnover",
    "KOT summary",
    "Item popularity",
    "Daily sales"
  ]
}'::jsonb),
  ('hotel', 'Hotel', true, '{
  "businessType": "hotel",
  "label": "Hotel",
  "sector": "Rooms & hospitality",
  "letter": "Ht",
  "hue": 210,
  "fields": {
    "required": [
      {
        "key": "room_type",
        "label": "Room type",
        "type": "select",
        "required": true,
        "options": [
          {
            "value": "standard",
            "label": "Standard"
          },
          {
            "value": "deluxe",
            "label": "Deluxe"
          },
          {
            "value": "executive",
            "label": "Executive"
          },
          {
            "value": "suite",
            "label": "Suite"
          }
        ]
      },
      {
        "key": "guest_name",
        "label": "Guest name",
        "type": "text",
        "required": true
      },
      {
        "key": "check_in",
        "label": "Check-in",
        "type": "date",
        "required": true
      },
      {
        "key": "check_out",
        "label": "Check-out",
        "type": "date",
        "required": true
      },
      {
        "key": "tariff",
        "label": "Tariff",
        "type": "currency",
        "required": true
      },
      {
        "key": "gst",
        "label": "GST",
        "type": "percent",
        "required": true
      }
    ],
    "optional": [
      {
        "key": "id_proof",
        "label": "ID proof",
        "type": "file",
        "required": false
      },
      {
        "key": "extra_bed",
        "label": "Extra bed",
        "type": "number",
        "required": false
      },
      {
        "key": "meal_plan",
        "label": "Meal plan",
        "type": "select",
        "required": false,
        "options": [
          {
            "value": "ep",
            "label": "EP — Room only"
          },
          {
            "value": "cp",
            "label": "CP — Breakfast"
          },
          {
            "value": "map",
            "label": "MAP — Breakfast + one meal"
          },
          {
            "value": "ap",
            "label": "AP — All meals"
          }
        ]
      }
    ]
  },
  "validations": [
    {
      "message": "Check-out must be after check-in",
      "check": {
        "kind": "date_after",
        "field": "check_out",
        "than": "check_in"
      }
    },
    {
      "message": "GST slab derived from room tariff",
      "check": {
        "kind": "note"
      }
    },
    {
      "message": "No-show / cancellation policy applied",
      "check": {
        "kind": "note"
      }
    }
  ],
  "gst": {
    "defaultLabel": "12%",
    "default": {
      "kind": "fixed",
      "bps": 1200
    },
    "slabs": [
      {
        "applies": "Tariff < ₹7,500",
        "rate": {
          "kind": "fixed",
          "bps": 1200
        },
        "when": {
          "op": "lt",
          "field": "$unit_price_paise",
          "value": 750000
        }
      },
      {
        "applies": "Tariff ≥ ₹7,500",
        "rate": {
          "kind": "fixed",
          "bps": 1800
        },
        "when": {
          "op": "gte",
          "field": "$unit_price_paise",
          "value": 750000
        }
      },
      {
        "applies": "Restaurant within hotel",
        "rate": {
          "kind": "range",
          "minBps": 500,
          "maxBps": 1800,
          "bps": 1800
        }
      }
    ]
  },
  "invoice": {
    "template": "GUEST FOLIO",
    "columns": [
      "Date",
      "Description",
      "Nights",
      "Rate",
      "GST",
      "Amount"
    ],
    "extras": [
      "Room + services split",
      "Guest ID recorded"
    ]
  },
  "reports": [
    "Occupancy",
    "Revenue per room",
    "ARR & RevPAR",
    "Advance bookings"
  ]
}'::jsonb),
  ('catering', 'Catering', true, '{
  "businessType": "catering",
  "label": "Catering",
  "sector": "Events & bulk food",
  "letter": "Ct",
  "hue": 50,
  "fields": {
    "required": [
      {
        "key": "event_date",
        "label": "Event date",
        "type": "date",
        "required": true
      },
      {
        "key": "item_name",
        "label": "Menu items",
        "type": "text",
        "required": true
      },
      {
        "key": "pax",
        "label": "Pax",
        "type": "number",
        "required": true
      },
      {
        "key": "rate_per_plate",
        "label": "Rate / plate",
        "type": "currency",
        "required": true
      },
      {
        "key": "gst",
        "label": "GST",
        "type": "percent",
        "required": true
      }
    ],
    "optional": [
      {
        "key": "venue",
        "label": "Venue",
        "type": "text",
        "required": false
      },
      {
        "key": "advance",
        "label": "Advance",
        "type": "currency",
        "required": false
      },
      {
        "key": "delivery_time",
        "label": "Delivery time",
        "type": "time",
        "required": false
      },
      {
        "key": "staff_count",
        "label": "Staff count",
        "type": "number",
        "required": false
      }
    ]
  },
  "validations": [
    {
      "message": "Pax must be greater than 0",
      "check": {
        "kind": "gt",
        "field": "pax",
        "value": 0
      }
    },
    {
      "message": "Advance cannot exceed total",
      "check": {
        "kind": "lte_field",
        "field": "advance",
        "than": "$line_total_paise"
      }
    },
    {
      "message": "Ingredient plan generated from pax",
      "check": {
        "kind": "note"
      }
    }
  ],
  "gst": {
    "defaultLabel": "5%",
    "default": {
      "kind": "fixed",
      "bps": 500
    },
    "slabs": [
      {
        "applies": "Outdoor catering",
        "rate": {
          "kind": "fixed",
          "bps": 500
        }
      },
      {
        "applies": "With premises / AC",
        "rate": {
          "kind": "fixed",
          "bps": 1800
        }
      }
    ]
  },
  "invoice": {
    "template": "QUOTATION / INVOICE",
    "columns": [
      "Menu",
      "Pax",
      "Rate/plate",
      "Amount"
    ],
    "extras": [
      "Advance received",
      "Balance due",
      "Event date"
    ]
  },
  "reports": [
    "Event calendar",
    "Advance due",
    "Ingredient plan",
    "Per-event margin"
  ]
}'::jsonb),
  ('manufacturing', 'Manufacturing', true, '{
  "businessType": "manufacturing",
  "label": "Manufacturing",
  "sector": "Production & assembly",
  "letter": "Mf",
  "hue": 200,
  "fields": {
    "required": [
      {
        "key": "item_name",
        "label": "Product",
        "type": "text",
        "required": true
      },
      {
        "key": "bom",
        "label": "BOM",
        "type": "text",
        "required": true
      },
      {
        "key": "qty",
        "label": "Qty produced",
        "type": "number",
        "required": true
      },
      {
        "key": "batch_no",
        "label": "Batch No",
        "type": "text",
        "required": true
      },
      {
        "key": "cost",
        "label": "Cost",
        "type": "currency",
        "required": true
      },
      {
        "key": "gst",
        "label": "GST",
        "type": "percent",
        "required": true
      }
    ],
    "optional": [
      {
        "key": "machine",
        "label": "Machine",
        "type": "select",
        "required": false,
        "options": [
          {
            "value": "line_1",
            "label": "Line 1"
          },
          {
            "value": "line_2",
            "label": "Line 2"
          },
          {
            "value": "manual",
            "label": "Manual"
          }
        ]
      },
      {
        "key": "shift",
        "label": "Shift",
        "type": "select",
        "required": false,
        "options": [
          {
            "value": "morning",
            "label": "Morning"
          },
          {
            "value": "evening",
            "label": "Evening"
          },
          {
            "value": "night",
            "label": "Night"
          }
        ]
      },
      {
        "key": "wastage_pct",
        "label": "Wastage %",
        "type": "percent",
        "required": false
      }
    ]
  },
  "validations": [
    {
      "message": "BOM raw materials must be in stock",
      "check": {
        "kind": "note"
      }
    },
    {
      "message": "Batch No mandatory per production run",
      "check": {
        "kind": "required_when",
        "field": "batch_no",
        "when": {
          "op": "present",
          "field": "item_name"
        }
      }
    },
    {
      "message": "Output qty updates finished-goods stock",
      "check": {
        "kind": "note"
      }
    }
  ],
  "gst": {
    "defaultLabel": "18%",
    "default": {
      "kind": "fixed",
      "bps": 1800
    },
    "slabs": [
      {
        "applies": "Standard goods",
        "rate": {
          "kind": "fixed",
          "bps": 1800
        }
      },
      {
        "applies": "Specific HSN slabs",
        "rate": {
          "kind": "range",
          "minBps": 500,
          "maxBps": 2800,
          "bps": 2800
        }
      }
    ]
  },
  "invoice": {
    "template": "TAX INVOICE",
    "columns": [
      "Product",
      "HSN",
      "Batch",
      "Qty",
      "Rate",
      "GST",
      "Amount"
    ],
    "extras": [
      "E-way bill",
      "HSN mandatory"
    ]
  },
  "reports": [
    "Production output",
    "Raw material consumption",
    "WIP status",
    "Product costing"
  ]
}'::jsonb),
  ('automobile', 'Automobile', true, '{
  "businessType": "automobile",
  "label": "Automobile",
  "sector": "Vehicles & service",
  "letter": "Au",
  "hue": 20,
  "fields": {
    "required": [
      {
        "key": "vehicle_no",
        "label": "Vehicle No",
        "type": "text",
        "required": true
      },
      {
        "key": "customer",
        "label": "Customer",
        "type": "text",
        "required": true
      },
      {
        "key": "item_name",
        "label": "Service / part",
        "type": "text",
        "required": true
      },
      {
        "key": "labour",
        "label": "Labour",
        "type": "currency",
        "required": true
      },
      {
        "key": "gst",
        "label": "GST",
        "type": "percent",
        "required": true
      }
    ],
    "optional": [
      {
        "key": "odometer",
        "label": "Odometer",
        "type": "number",
        "required": false
      },
      {
        "key": "next_service_date",
        "label": "Next service date",
        "type": "date",
        "required": false
      },
      {
        "key": "warranty",
        "label": "Warranty",
        "type": "select",
        "required": false,
        "options": [
          {
            "value": "none",
            "label": "No warranty"
          },
          {
            "value": "6m",
            "label": "6 months"
          },
          {
            "value": "1y",
            "label": "1 year"
          },
          {
            "value": "2y",
            "label": "2 years"
          },
          {
            "value": "3y",
            "label": "3 years"
          }
        ]
      }
    ]
  },
  "validations": [
    {
      "message": "Vehicle No format validated",
      "check": {
        "kind": "note"
      }
    },
    {
      "message": "Parts and labour taxed under correct HSN/SAC",
      "check": {
        "kind": "note"
      }
    },
    {
      "message": "Service-due reminder scheduled",
      "check": {
        "kind": "note"
      }
    }
  ],
  "gst": {
    "defaultLabel": "18%",
    "default": {
      "kind": "fixed",
      "bps": 1800
    },
    "slabs": [
      {
        "applies": "Spare parts",
        "rate": {
          "kind": "range",
          "minBps": 1800,
          "maxBps": 2800,
          "bps": 2800
        }
      },
      {
        "applies": "Labour (SAC)",
        "rate": {
          "kind": "fixed",
          "bps": 1800
        }
      }
    ]
  },
  "invoice": {
    "template": "JOB CARD / INVOICE",
    "columns": [
      "Description",
      "Type",
      "Qty",
      "Rate",
      "GST",
      "Amount"
    ],
    "extras": [
      "Parts + labour split",
      "Vehicle No recorded"
    ]
  },
  "reports": [
    "Job cards",
    "Parts ledger",
    "Service-due reminders",
    "Technician load"
  ]
}'::jsonb),
  ('jewellery', 'Jewellery', true, '{
  "businessType": "jewellery",
  "label": "Jewellery",
  "sector": "Gold & silver",
  "letter": "Jw",
  "hue": 85,
  "fields": {
    "required": [
      {
        "key": "item_name",
        "label": "Item",
        "type": "text",
        "required": true
      },
      {
        "key": "purity",
        "label": "Purity",
        "type": "select",
        "required": true,
        "options": [
          {
            "value": "24k",
            "label": "24K"
          },
          {
            "value": "22k",
            "label": "22K"
          },
          {
            "value": "18k",
            "label": "18K"
          },
          {
            "value": "14k",
            "label": "14K"
          },
          {
            "value": "silver_925",
            "label": "925 Silver"
          }
        ]
      },
      {
        "key": "gross_wt",
        "label": "Gross wt (g)",
        "type": "number",
        "required": true,
        "unit": "g"
      },
      {
        "key": "net_wt",
        "label": "Net wt (g)",
        "type": "number",
        "required": true,
        "unit": "g"
      },
      {
        "key": "rate_per_g",
        "label": "Rate / g",
        "type": "currency",
        "required": true,
        "unit": "g"
      },
      {
        "key": "making_charge",
        "label": "Making charge",
        "type": "percent",
        "required": true
      },
      {
        "key": "gst",
        "label": "GST",
        "type": "percent",
        "required": true
      }
    ],
    "optional": [
      {
        "key": "stone_wt",
        "label": "Stone wt",
        "type": "number",
        "required": false
      },
      {
        "key": "huid",
        "label": "HUID",
        "type": "text",
        "required": false
      },
      {
        "key": "hallmark_no",
        "label": "Hallmark no",
        "type": "text",
        "required": false
      }
    ]
  },
  "validations": [
    {
      "message": "Net weight cannot exceed gross weight",
      "check": {
        "kind": "lte_field",
        "field": "net_wt",
        "than": "gross_wt"
      }
    },
    {
      "message": "HUID must be 6 characters",
      "check": {
        "kind": "length",
        "field": "huid",
        "exact": 6
      }
    },
    {
      "message": "Value = metal + making + GST",
      "check": {
        "kind": "note"
      }
    },
    {
      "message": "Old-gold exchange deducted before tax",
      "check": {
        "kind": "note"
      }
    }
  ],
  "gst": {
    "defaultLabel": "3%",
    "default": {
      "kind": "fixed",
      "bps": 300
    },
    "slabs": [
      {
        "applies": "Gold & silver ornaments",
        "rate": {
          "kind": "fixed",
          "bps": 300
        }
      },
      {
        "applies": "Making charges",
        "rate": {
          "kind": "fixed",
          "bps": 500
        }
      }
    ]
  },
  "invoice": {
    "template": "TAX INVOICE",
    "columns": [
      "Item",
      "Purity",
      "Gross",
      "Net",
      "Rate/g",
      "Making",
      "GST",
      "Amount"
    ],
    "extras": [
      "HUID printed",
      "Hallmark details"
    ]
  },
  "reports": [
    "Metal (gold/silver) ledger",
    "Making-charge summary",
    "Hallmark log",
    "Old-gold exchange"
  ]
}'::jsonb),
  ('garments', 'Garments', true, '{
  "businessType": "garments",
  "label": "Garments",
  "sector": "Apparel & textile",
  "letter": "Ga",
  "hue": 350,
  "fields": {
    "required": [
      {
        "key": "sku",
        "label": "Style / SKU",
        "type": "text",
        "required": true
      },
      {
        "key": "size",
        "label": "Size",
        "type": "select",
        "required": true,
        "options": [
          {
            "value": "xs",
            "label": "XS"
          },
          {
            "value": "s",
            "label": "S"
          },
          {
            "value": "m",
            "label": "M"
          },
          {
            "value": "l",
            "label": "L"
          },
          {
            "value": "xl",
            "label": "XL"
          },
          {
            "value": "xxl",
            "label": "XXL"
          },
          {
            "value": "free",
            "label": "Free size"
          }
        ]
      },
      {
        "key": "colour",
        "label": "Colour",
        "type": "select",
        "required": true,
        "options": [
          {
            "value": "black",
            "label": "Black"
          },
          {
            "value": "white",
            "label": "White"
          },
          {
            "value": "blue",
            "label": "Blue"
          },
          {
            "value": "red",
            "label": "Red"
          },
          {
            "value": "green",
            "label": "Green"
          },
          {
            "value": "grey",
            "label": "Grey"
          },
          {
            "value": "silver",
            "label": "Silver"
          },
          {
            "value": "gold",
            "label": "Gold"
          },
          {
            "value": "other",
            "label": "Other"
          }
        ]
      },
      {
        "key": "mrp",
        "label": "MRP",
        "type": "currency",
        "required": true
      },
      {
        "key": "qty",
        "label": "Qty",
        "type": "number",
        "required": true
      },
      {
        "key": "gst",
        "label": "GST",
        "type": "percent",
        "required": true
      }
    ],
    "optional": [
      {
        "key": "hsn",
        "label": "HSN",
        "type": "text",
        "required": false
      },
      {
        "key": "fabric",
        "label": "Fabric",
        "type": "text",
        "required": false
      },
      {
        "key": "brand",
        "label": "Brand",
        "type": "select",
        "required": false,
        "options": [
          {
            "value": "in_house",
            "label": "In-house"
          },
          {
            "value": "local",
            "label": "Local"
          },
          {
            "value": "other",
            "label": "Other"
          }
        ]
      }
    ]
  },
  "validations": [
    {
      "message": "SKU unique per size + colour",
      "check": {
        "kind": "unique",
        "fields": [
          "sku",
          "size",
          "colour"
        ]
      }
    },
    {
      "message": "GST slab depends on price point",
      "check": {
        "kind": "note"
      }
    },
    {
      "message": "Size-colour matrix keeps stock",
      "check": {
        "kind": "note"
      }
    }
  ],
  "gst": {
    "defaultLabel": "5%",
    "default": {
      "kind": "fixed",
      "bps": 500
    },
    "slabs": [
      {
        "applies": "Apparel < ₹1,000",
        "rate": {
          "kind": "fixed",
          "bps": 500
        },
        "when": {
          "op": "lt",
          "field": "$unit_price_paise",
          "value": 100000
        }
      },
      {
        "applies": "Apparel ≥ ₹1,000",
        "rate": {
          "kind": "fixed",
          "bps": 1200
        },
        "when": {
          "op": "gte",
          "field": "$unit_price_paise",
          "value": 100000
        }
      }
    ]
  },
  "invoice": {
    "template": "TAX INVOICE",
    "columns": [
      "Style",
      "Size",
      "Colour",
      "Qty",
      "Rate",
      "GST",
      "Amount"
    ],
    "extras": [
      "Size-colour matrix"
    ]
  },
  "reports": [
    "Size-wise sales",
    "SKU stock",
    "Season trend",
    "Dead stock"
  ]
}'::jsonb),
  ('furniture', 'Furniture', true, '{
  "businessType": "furniture",
  "label": "Furniture",
  "sector": "Home & office",
  "letter": "Fu",
  "hue": 60,
  "fields": {
    "required": [
      {
        "key": "item_name",
        "label": "Item",
        "type": "text",
        "required": true
      },
      {
        "key": "material",
        "label": "Material",
        "type": "select",
        "required": true,
        "options": [
          {
            "value": "wood",
            "label": "Wood"
          },
          {
            "value": "plywood",
            "label": "Plywood / MDF"
          },
          {
            "value": "metal",
            "label": "Metal"
          },
          {
            "value": "modular",
            "label": "Modular"
          },
          {
            "value": "plastic",
            "label": "Plastic"
          },
          {
            "value": "glass",
            "label": "Glass"
          }
        ]
      },
      {
        "key": "dimensions",
        "label": "Dimensions",
        "type": "text",
        "required": true
      },
      {
        "key": "price",
        "label": "Price",
        "type": "currency",
        "required": true
      },
      {
        "key": "qty",
        "label": "Qty",
        "type": "number",
        "required": true
      },
      {
        "key": "gst",
        "label": "GST",
        "type": "percent",
        "required": true
      }
    ],
    "optional": [
      {
        "key": "warranty",
        "label": "Warranty",
        "type": "select",
        "required": false,
        "options": [
          {
            "value": "none",
            "label": "No warranty"
          },
          {
            "value": "6m",
            "label": "6 months"
          },
          {
            "value": "1y",
            "label": "1 year"
          },
          {
            "value": "2y",
            "label": "2 years"
          },
          {
            "value": "3y",
            "label": "3 years"
          }
        ]
      },
      {
        "key": "assembly",
        "label": "Assembly",
        "type": "boolean",
        "required": false
      },
      {
        "key": "delivery_date",
        "label": "Delivery date",
        "type": "date",
        "required": false
      }
    ]
  },
  "validations": [
    {
      "message": "Delivery date must be on/after order date",
      "check": {
        "kind": "date_after",
        "field": "delivery_date",
        "than": "$today",
        "orEqual": true
      }
    },
    {
      "message": "Assembly charge added when selected",
      "check": {
        "kind": "note"
      }
    },
    {
      "message": "Made-to-order needs advance",
      "check": {
        "kind": "note"
      }
    }
  ],
  "gst": {
    "defaultLabel": "18%",
    "default": {
      "kind": "fixed",
      "bps": 1800
    },
    "slabs": [
      {
        "applies": "Wooden furniture",
        "rate": {
          "kind": "fixed",
          "bps": 1200
        }
      },
      {
        "applies": "Metal / modular",
        "rate": {
          "kind": "fixed",
          "bps": 1800
        }
      }
    ]
  },
  "invoice": {
    "template": "TAX INVOICE",
    "columns": [
      "Item",
      "Material",
      "Dimensions",
      "Qty",
      "Rate",
      "GST",
      "Amount"
    ],
    "extras": [
      "Delivery & assembly",
      "Warranty terms"
    ]
  },
  "reports": [
    "Order pipeline",
    "Delivery schedule",
    "Material stock",
    "Made-to-order status"
  ]
}'::jsonb),
  ('hardware', 'Hardware', true, '{
  "businessType": "hardware",
  "label": "Hardware",
  "sector": "Tools & building",
  "letter": "Hw",
  "hue": 215,
  "fields": {
    "required": [
      {
        "key": "item_name",
        "label": "Item",
        "type": "text",
        "required": true
      },
      {
        "key": "unit",
        "label": "Unit",
        "type": "select",
        "required": true,
        "options": [
          {
            "value": "pcs",
            "label": "Pieces"
          },
          {
            "value": "kg",
            "label": "Kilogram"
          },
          {
            "value": "g",
            "label": "Gram"
          },
          {
            "value": "ltr",
            "label": "Litre"
          },
          {
            "value": "ml",
            "label": "Millilitre"
          },
          {
            "value": "box",
            "label": "Box"
          },
          {
            "value": "mtr",
            "label": "Metre"
          }
        ]
      },
      {
        "key": "qty",
        "label": "Qty",
        "type": "number",
        "required": true
      },
      {
        "key": "rate",
        "label": "Rate",
        "type": "currency",
        "required": true
      },
      {
        "key": "gst",
        "label": "GST",
        "type": "percent",
        "required": true
      }
    ],
    "optional": [
      {
        "key": "hsn",
        "label": "HSN",
        "type": "text",
        "required": false
      },
      {
        "key": "brand",
        "label": "Brand",
        "type": "select",
        "required": false,
        "options": [
          {
            "value": "havells",
            "label": "Havells"
          },
          {
            "value": "finolex",
            "label": "Finolex"
          },
          {
            "value": "astral",
            "label": "Astral"
          },
          {
            "value": "asian_paints",
            "label": "Asian Paints"
          },
          {
            "value": "local",
            "label": "Local"
          },
          {
            "value": "other",
            "label": "Other"
          }
        ]
      },
      {
        "key": "barcode",
        "label": "Barcode",
        "type": "scan",
        "required": false,
        "scanKind": "barcode"
      }
    ]
  },
  "validations": [
    {
      "message": "Quantity must be greater than 0",
      "check": {
        "kind": "gt",
        "field": "qty",
        "value": 0
      }
    },
    {
      "message": "Unit conversions kept consistent",
      "check": {
        "kind": "note"
      }
    },
    {
      "message": "Slab varies by HSN",
      "check": {
        "kind": "note"
      }
    }
  ],
  "gst": {
    "defaultLabel": "18%",
    "default": {
      "kind": "fixed",
      "bps": 1800
    },
    "slabs": [
      {
        "applies": "Fittings & pipes",
        "rate": {
          "kind": "fixed",
          "bps": 1800
        }
      },
      {
        "applies": "Cement / paint",
        "rate": {
          "kind": "fixed",
          "bps": 2800
        }
      }
    ]
  },
  "invoice": {
    "template": "TAX INVOICE",
    "columns": [
      "Item",
      "Unit",
      "Qty",
      "Rate",
      "GST",
      "Amount"
    ],
    "extras": [
      "Unit-based pricing"
    ]
  },
  "reports": [
    "Stock by unit",
    "Supplier dues",
    "GST summary",
    "Bulk orders"
  ]
}'::jsonb),
  ('wholesale', 'Wholesale', true, '{
  "businessType": "wholesale",
  "label": "Wholesale",
  "sector": "Bulk B2B trade",
  "letter": "Wh",
  "hue": 190,
  "fields": {
    "required": [
      {
        "key": "item_name",
        "label": "Item",
        "type": "text",
        "required": true
      },
      {
        "key": "qty",
        "label": "Qty",
        "type": "number",
        "required": true
      },
      {
        "key": "rate",
        "label": "Rate",
        "type": "currency",
        "required": true
      },
      {
        "key": "gst",
        "label": "GST",
        "type": "percent",
        "required": true
      },
      {
        "key": "party_gstin",
        "label": "Party GSTIN",
        "type": "text",
        "required": true
      }
    ],
    "optional": [
      {
        "key": "discount_slab",
        "label": "Discount slab",
        "type": "percent",
        "required": false
      },
      {
        "key": "credit_days",
        "label": "Credit days",
        "type": "number",
        "required": false
      },
      {
        "key": "transport",
        "label": "Transport",
        "type": "text",
        "required": false
      }
    ]
  },
  "validations": [
    {
      "message": "Party GSTIN must be valid (15 chars)",
      "check": {
        "kind": "gstin",
        "field": "party_gstin"
      }
    },
    {
      "message": "Credit within party limit",
      "check": {
        "kind": "note"
      }
    },
    {
      "message": "E-way bill for invoices above threshold",
      "check": {
        "kind": "note"
      }
    }
  ],
  "gst": {
    "defaultLabel": "As per HSN",
    "default": {
      "kind": "hsn"
    },
    "slabs": [
      {
        "applies": "Rate follows item HSN",
        "rate": {
          "kind": "hsn"
        }
      },
      {
        "applies": "Inter-state",
        "rate": {
          "kind": "igst"
        }
      }
    ]
  },
  "invoice": {
    "template": "TAX INVOICE (B2B)",
    "columns": [
      "Item",
      "HSN",
      "Qty",
      "Rate",
      "Disc",
      "GST",
      "Amount"
    ],
    "extras": [
      "E-way bill",
      "Party GSTIN"
    ]
  },
  "reports": [
    "Party outstanding",
    "Bulk movers",
    "Margin analysis",
    "Credit ageing"
  ]
}'::jsonb),
  ('retail', 'Retail', true, '{
  "businessType": "retail",
  "label": "Retail",
  "sector": "General store / POS",
  "letter": "Rl",
  "hue": 280,
  "fields": {
    "required": [
      {
        "key": "item_name",
        "label": "Item",
        "type": "text",
        "required": true
      },
      {
        "key": "qty",
        "label": "Qty",
        "type": "number",
        "required": true
      },
      {
        "key": "rate",
        "label": "Rate",
        "type": "currency",
        "required": true
      },
      {
        "key": "gst",
        "label": "GST",
        "type": "percent",
        "required": true
      }
    ],
    "optional": [
      {
        "key": "barcode",
        "label": "Barcode",
        "type": "scan",
        "required": false,
        "scanKind": "barcode"
      },
      {
        "key": "customer",
        "label": "Customer",
        "type": "select",
        "required": false,
        "options": [
          {
            "value": "walk_in",
            "label": "Walk-in"
          },
          {
            "value": "registered",
            "label": "Registered customer"
          }
        ]
      },
      {
        "key": "discount",
        "label": "Discount",
        "type": "percent",
        "required": false
      }
    ]
  },
  "validations": [
    {
      "message": "Qty cannot exceed stock",
      "check": {
        "kind": "lte_field",
        "field": "qty",
        "than": "$available_stock"
      }
    },
    {
      "message": "GST per item HSN",
      "check": {
        "kind": "note"
      }
    },
    {
      "message": "Discount within allowed limit",
      "check": {
        "kind": "note"
      }
    }
  ],
  "gst": {
    "defaultLabel": "As per HSN",
    "default": {
      "kind": "hsn"
    },
    "slabs": [
      {
        "applies": "Rate follows item HSN",
        "rate": {
          "kind": "hsn"
        }
      }
    ]
  },
  "invoice": {
    "template": "RETAIL BILL",
    "columns": [
      "Item",
      "Qty",
      "Rate",
      "Disc",
      "GST",
      "Amount"
    ],
    "extras": [
      "POS quick-bill",
      "Loyalty points"
    ]
  },
  "reports": [
    "Daily sales",
    "Fast movers",
    "Average bill value",
    "Hourly footfall"
  ]
}'::jsonb),
  ('distributor', 'Distributor', true, '{
  "businessType": "distributor",
  "label": "Distributor",
  "sector": "Supply & route sales",
  "letter": "Ds",
  "hue": 170,
  "fields": {
    "required": [
      {
        "key": "item_name",
        "label": "Item",
        "type": "text",
        "required": true
      },
      {
        "key": "batch_no",
        "label": "Batch",
        "type": "text",
        "required": true
      },
      {
        "key": "qty",
        "label": "Qty",
        "type": "number",
        "required": true
      },
      {
        "key": "rate",
        "label": "Rate",
        "type": "currency",
        "required": true
      },
      {
        "key": "gst",
        "label": "GST",
        "type": "percent",
        "required": true
      },
      {
        "key": "party_gstin",
        "label": "Retailer GSTIN",
        "type": "text",
        "required": true
      }
    ],
    "optional": [
      {
        "key": "scheme",
        "label": "Scheme",
        "type": "text",
        "required": false
      },
      {
        "key": "credit_days",
        "label": "Credit days",
        "type": "number",
        "required": false
      },
      {
        "key": "route",
        "label": "Route",
        "type": "select",
        "required": false,
        "options": [
          {
            "value": "north",
            "label": "North"
          },
          {
            "value": "south",
            "label": "South"
          },
          {
            "value": "east",
            "label": "East"
          },
          {
            "value": "west",
            "label": "West"
          },
          {
            "value": "local",
            "label": "Local"
          }
        ]
      },
      {
        "key": "salesman",
        "label": "Salesman",
        "type": "select",
        "required": false,
        "options": [
          {
            "value": "unassigned",
            "label": "Unassigned"
          },
          {
            "value": "staff_1",
            "label": "Staff 1"
          },
          {
            "value": "staff_2",
            "label": "Staff 2"
          },
          {
            "value": "staff_3",
            "label": "Staff 3"
          }
        ]
      }
    ]
  },
  "validations": [
    {
      "message": "Scheme discount within margin",
      "check": {
        "kind": "note"
      }
    },
    {
      "message": "Retailer GSTIN valid",
      "check": {
        "kind": "gstin",
        "field": "party_gstin"
      }
    },
    {
      "message": "Batch tracked for secondary sales",
      "check": {
        "kind": "note"
      }
    },
    {
      "message": "E-way bill above threshold",
      "check": {
        "kind": "note"
      }
    }
  ],
  "gst": {
    "defaultLabel": "As per HSN",
    "default": {
      "kind": "hsn"
    },
    "slabs": [
      {
        "applies": "Rate follows item HSN",
        "rate": {
          "kind": "hsn"
        }
      },
      {
        "applies": "Scheme discount pre-tax",
        "rate": {
          "kind": "none"
        }
      }
    ]
  },
  "invoice": {
    "template": "TAX INVOICE (B2B)",
    "columns": [
      "Item",
      "Batch",
      "Qty",
      "Rate",
      "Scheme",
      "GST",
      "Amount"
    ],
    "extras": [
      "E-way bill",
      "Route / salesman"
    ]
  },
  "reports": [
    "Route sales",
    "Scheme cost",
    "Secondary sales",
    "Outstanding by retailer"
  ]
}'::jsonb),
  ('diagnostics', 'Diagnostic Centre', true, '{
  "businessType": "diagnostics",
  "label": "Diagnostic Centre",
  "sector": "Pathology & imaging",
  "letter": "Dx",
  "hue": 196,
  "fields": {
    "required": [
      {
        "key": "item_name",
        "label": "Test / scan",
        "type": "text",
        "required": true
      },
      {
        "key": "patient_name",
        "label": "Patient name",
        "type": "text",
        "required": true
      },
      {
        "key": "qty",
        "label": "Qty",
        "type": "number",
        "required": true
      },
      {
        "key": "rate",
        "label": "Rate",
        "type": "currency",
        "required": true
      },
      {
        "key": "gst",
        "label": "GST",
        "type": "percent",
        "required": true
      }
    ],
    "optional": [
      {
        "key": "sample_id",
        "label": "Sample ID",
        "type": "scan",
        "required": false,
        "scanKind": "barcode"
      },
      {
        "key": "referred_by",
        "label": "Referred by",
        "type": "text",
        "required": false
      },
      {
        "key": "collected_on",
        "label": "Collected on",
        "type": "date",
        "required": false
      },
      {
        "key": "report_due",
        "label": "Report due",
        "type": "date",
        "required": false
      },
      {
        "key": "sac",
        "label": "SAC",
        "type": "text",
        "required": false
      }
    ]
  },
  "validations": [
    {
      "message": "Sample ID must be unique",
      "check": {
        "kind": "unique",
        "fields": [
          "sample_id"
        ]
      }
    },
    {
      "message": "Report due cannot be before the collection date",
      "check": {
        "kind": "date_after",
        "field": "report_due",
        "than": "collected_on",
        "orEqual": true
      }
    },
    {
      "message": "Rate must be greater than 0",
      "check": {
        "kind": "gt",
        "field": "rate",
        "value": 0
      }
    },
    {
      "message": "Healthcare diagnostics are GST-exempt — issue a bill of supply, not a tax invoice",
      "check": {
        "kind": "note"
      }
    },
    {
      "message": "Referring doctor required for a TPA or insurance claim",
      "check": {
        "kind": "note"
      }
    }
  ],
  "gst": {
    "defaultLabel": "Exempt",
    "default": {
      "kind": "fixed",
      "bps": 0
    },
    "exempt": true,
    "slabs": [
      {
        "applies": "Diagnostic & pathology services",
        "rate": {
          "kind": "fixed",
          "bps": 0
        }
      },
      {
        "applies": "Non-clinical services (reports, records)",
        "rate": {
          "kind": "fixed",
          "bps": 1800
        }
      }
    ]
  },
  "invoice": {
    "template": "BILL OF SUPPLY",
    "columns": [
      "Test",
      "Patient",
      "Qty",
      "Rate",
      "Amount"
    ],
    "extras": [
      "Referring doctor",
      "Report collection date",
      "Lab in-charge sign"
    ]
  },
  "reports": [
    "Test-wise revenue",
    "Referring doctor register",
    "Pending reports",
    "Daily collections"
  ]
}'::jsonb)
on conflict (key) do update
  set label = excluded.label,
      config = excluded.config,
      is_system = true;

-- Retire the placeholder verticals. Only ever touches system rows that no org
-- points at — an org on a retired key keeps it rather than silently becoming a
-- pharmacy, and a tenant's own custom vertical (is_system = false) is never in
-- scope here.
delete from public.business_types bt
where bt.is_system = true
  and bt.key not in ('pharmacy', 'medical', 'grocery', 'kirana', 'electronics', 'mobile', 'restaurant', 'hotel', 'catering', 'manufacturing', 'automobile', 'jewellery', 'garments', 'furniture', 'hardware', 'wholesale', 'retail', 'distributor', 'diagnostics')
  and not exists (
    select 1 from public.organizations o where o.business_type_id = bt.id
  );
