import nextPlugin from "@next/eslint-plugin-next";

import { reactConfig } from "./react.js";

/**
 * Config for the Next.js apps (apps/web, apps/admin).
 *
 * Uses the plugin directly rather than `eslint-config-next`, which is still
 * eslintrc-shaped and would need FlatCompat to load.
 * @type {import("eslint").Linter.Config[]}
 */
export const nextConfig = [
  ...reactConfig,
  {
    plugins: { "@next/next": nextPlugin },
    rules: {
      ...nextPlugin.configs.recommended.rules,
      ...nextPlugin.configs["core-web-vitals"].rules,
    },
  },
  {
    // Regenerated by Next on every build; Next owns its contents.
    ignores: ["next-env.d.ts"],
  },
];

export default nextConfig;
